"use strict";


var app = require('../app');


app.directive('noTransclude',function(){
	return {
		restrict: 'E',
		scope: {

		},
		template: '<div>This is this text generated by the directive</div>'
	}

}).directive('usingTransclude',function(){
	return {
		restrict: 'E',
		transclude: true,
		scope: {

		},
		template: '<div>This is this text generated by the directive <br><span ng-transclude></span></div>'
	}

});




module.exports = app;

